version: 2

sources:
  - name: resale
    description: >
      HDB resale with resale_flat_prices_from_jan_20 DASI first project  dataset from BigQuery.
    database: dasi-first-project
    schema: resale
    
    tables:
      - name: public_resale_flat_prices_from_jan_2017
        description: >
          resale flat rices from January 2017 onwards.
          